name: Matrix is empty
on: push

jobs:
  prepare_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      empty: ${{ steps.has-matrix.outputs.empty }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - id: Set matrix
        name: Set the matrix
        run: echo "::set-output name=matrix::{\"include\":[]}"

      - id: has-matrix
        name: Matrix is empty
        run: echo "::set-output name=empty::true"

  job1:
    runs-on: ubuntu-latest
    needs: prepare_matrix
    if: ${{ needs.prepare_matrix.outputs.empty == 'false' }}
    strategy:
      matrix: ${{ fromJson(needs.prepare_matrix.outputs.matrix) }}
    steps:
      - run: echo "Project Name -- ${{ matrix.project }}"
